[project]
name = "clinkey"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.7"
dependencies = [
    "click>=8.3.0",
    "rich>=14.1.0",
    "rich-click>=1.9.1",
]
